// <auto-generated />
using System;
using EFCore.ModelExtras.Example;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.ModelExtras.Example.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    partial class ExampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jp_DeclareFunction_log_user_email_change", "{\"Source\":\"CREATE OR REPLACE FUNCTION log_user_email_change()\\n  RETURNS trigger\\n  LANGUAGE plpgsql\\nAS $function$\\nBEGIN\\n    -- Only log if email actually changed\\n    IF (TG_OP = \\u0027UPDATE\\u0027 AND OLD.email IS DISTINCT FROM NEW.email) THEN\\n        INSERT INTO email_audit_logs (user_id, old_email, new_email, changed_at)\\n        VALUES (NEW.id, OLD.email, NEW.email, NOW());\\n    END IF;\\n\\n    RETURN NEW;\\nEND;\\n$function$\",\"OverloadDiscriminator\":\"\",\"Name\":\"log_user_email_change\"}")
                .HasAnnotation("Jp_DeclareFunction_update_timestamp", "{\"Source\":\"CREATE OR REPLACE FUNCTION update_timestamp()\\n  RETURNS trigger\\n  LANGUAGE plpgsql\\nAS $function$\\nBEGIN\\n    NEW.updated_at = NOW();\\n    RETURN NEW;\\nEND;\\n$function$\",\"OverloadDiscriminator\":\"\",\"Name\":\"update_timestamp\"}")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCore.ModelExtras.Example.EmailAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OldEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmailAuditLogs");
                });

            modelBuilder.Entity("EFCore.ModelExtras.Example.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b
                        .HasAnnotation("Jp_HasTrigger_tu_user_email_audit", "{\"TriggerTiming\":1,\"TriggerEvent\":[{\"Event\":1,\"ColumnsForUpdate\":[\"email\"]}],\"Source\":\"FOR EACH ROW\\nEXECUTE FUNCTION log_user_email_change()\",\"IsConstraintTrigger\":false,\"Name\":\"tu_user_email_audit\"}")
                        .HasAnnotation("Jp_HasTrigger_tu_user_update_timestamp", "{\"TriggerTiming\":0,\"TriggerEvent\":[{\"Event\":1,\"ColumnsForUpdate\":[]}],\"Source\":\"FOR EACH ROW\\nEXECUTE FUNCTION update_timestamp()\",\"IsConstraintTrigger\":false,\"Name\":\"tu_user_update_timestamp\"}");
                });
#pragma warning restore 612, 618
        }
    }
}
